# Generated by Django 4.2.29 on 2026-04-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_genre_story_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='security_answer_hash',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='security_question',
        ),
    ]
